WITH COUNT_OF_PILLS AS 
(	
	SELECT YEAR_MONTH, SUM(DOSAGE_UNIT) AS DOSAGE_COUNT FROM
	(
		SELECT 
		(YEAR(TRANSACTION_DATE) ||
			CASE 
	    	WHEN (  CAST( MONTH(TRANSACTION_DATE) AS INT)  < 10 ) 
	         	THEN '0'  || CAST( MONTH(TRANSACTION_DATE) AS INT)
	    	ELSE CAST ( MONTH(TRANSACTION_DATE) AS CHAR(2) )
			END
		) AS YEAR_MONTH,
		DOSAGE_UNIT
		FROM CSE532.DEA_NY
	)
	GROUP BY YEAR_MONTH	
) 

SELECT YEAR_MONTH, DOSAGE_COUNT, AVG(DOSAGE_COUNT) OVER
	(ORDER BY YEAR_MONTH ROWS BETWEEN 1 PRECEDING AND 1 FOLLOWING) 
	AS DOSAGE_SMOOTH_COUNT
FROM COUNT_OF_PILLS;